backend:
  name: github
  repo: nspilman/bahblog-gridsome

media_folder: "static/uploads"
public_folder: "/uploads"

collections:
  - name: "travel"
    label: "Posts"
    folder: "travel"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "string"}
      - {label: "Featured Image", name: "image", widget: "image", default: "../img/globe.jpg"}
      - {label: "Publish Date", name: "date", widget: "date"}
      - {label: "Tags", name: "tags", widget: "list"}
      - {label: "Published", name: "published", widget: "boolean", default: false}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "recipe"
    label: "Recipes"
    folder: "recipes"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "string"}
      - {label: "Featured Image", name: "image", widget: "image", default: "../img/globe.jpg"}
      - {label: "Publish Date", name: "date", widget: "date"}
      - {label: "Prep Time", name: "preptime", widget: "string"}
      - {label: "Cook Time", name: "cooktime", widget: "string"}
      - {label: "Tags", name: "tags", widget: "list"}
      - {label: "Ingredients", name: "ingredients", widget: "list"}
      - {label: "Directions", name: "directions", widget: "list"}
      - {label: "Published", name: "published", widget: "boolean", default: false}
      - {label: "Body", name: "body", widget: "markdown"}